CREATE TABLE  "SYSLOG" 
   (	"ID" NUMBER, 
	"REMOTEIP" VARCHAR2(250), 
	"APPNAME" VARCHAR2(50), 
	"ZEIT" VARCHAR2(40), 
	"HOSTNAME" VARCHAR2(250), 
	"PID" NUMBER, 
	"PRIORITY" NUMBER, 
	"MESSAGE" VARCHAR2(2000), 
	"SYSDATUM" TIMESTAMP (6), 
	"GUID" VARCHAR2(40), 
	 CONSTRAINT "SYSLOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )   NO INMEMORY
/

CREATE SEQUENCE   "SYSLOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_SYSLOG" 
  before insert on "SYSLOG"               
  for each row  
begin 
  if :NEW."ID" is null then 
    select "SYSLOG_SEQ1".nextval into :NEW."ID" from sys.dual; 
    :NEW."SYSDATUM" := systimestamp;
  end if; 
end; 

/
ALTER TRIGGER  "BI_SYSLOG" ENABLE
/


